services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    ports:
      - 3000:3000/tcp
    environment:
      GF_DEFAULT_APP_MODE: development
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/panels.json
      GF_PLUGINS_PREINSTALL: marcusolsson-static-datasource,marcusolsson-json-datasource,volkovlabs-variable-panel, volkovlabs-image-panel
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/login"]
      interval: 30s
      timeout: 5s
      retries: 5

  server-json:
    build:
      context: ./server-json
    ports:
      - 3001:3001/tcp
    profiles:
      - dev
      - prod
      - playwright

  server-delay:
    build:
      context: ./server-delay
    ports:
      - 5002:5002/tcp
    profiles:
      - dev
      - prod
      - playwright

  postgres:
    image: postgres@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./server-pg:/docker-entrypoint-initdb.d
    profiles:
      - dev
      - prod
      - playwright

  server-postgres:
    build:
      context: ./server-pg
    ports:
      - 3002:3001/tcp
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    profiles:
      - dev
      - prod
      - playwright

  playwright:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
      - ./provisioning:/app/provisioning
      - ./playwright.config.ts:/app/playwright.config.ts
    depends_on:
      grafana:
        condition: service_healthy
    profiles:
      - playwright
